# Chi-Square Test for Independence

The **Chi-Square Test for Independence** is a statistical test used to determine whether there is a **significant association** between two **categorical variables**.

---

## 🔹 Definition

The Chi-Square Test for Independence helps us check whether two variables are **independent** or **related** to each other.

It compares the **observed frequencies** (actual data) with the **expected frequencies** (data we would expect if the variables were independent).

---

## 🔹 Formula

The formula for the Chi-Square statistic is:

$$
\chi^2 = \sum \frac{(O - E)^2}{E}
$$

Where:

- $O$ = Observed frequency  
- $E$ = Expected frequency  
- $\sum$ = Summation over all possible categories  

---

## 🔹 Expected Frequency Formula

Expected frequency for each cell is calculated as:

$$
E = \frac{(\text{Row Total}) \times (\text{Column Total})}{\text{Grand Total}}
$$

---

## 🔹 Hypotheses

- **Null Hypothesis ($H_0$):** The two variables are independent.  
- **Alternative Hypothesis ($H_1$):** The two variables are not independent (there is an association).

---

## 🔹 Degrees of Freedom (df)

The degrees of freedom for the test are given by:

$$
df = (r - 1)(c - 1)
$$

Where:
- $r$ = Number of rows  
- $c$ = Number of columns  

---

## 🔹 Decision Rule

- If the calculated value of $\chi^2$ > critical value from Chi-Square table → **Reject $H_0$**  
- Otherwise → **Fail to reject $H_0$**

---

## 🔹 Example (Conceptual)

Suppose we want to test whether **gender** and **preference for a product** are related.  
We collect data and create a contingency table, then apply the Chi-Square formula to test independence.

---

## ✅ Conclusion

The **Chi-Square Test for Independence** helps determine whether two categorical variables have a **statistically significant relationship** or not.  
It is commonly used in **survey analysis, ma**


In [2]:

import seaborn as sns
import numpy as np
import pandas as pd
from scipy.stats import chi2, chi2_contingency

In [3]:
data = sns.load_dataset('tips')

In [4]:
data.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

### Example — Chi-Square Test for Independence

We are testing whether **Smoker** and **Gender** are independent in the **Tips dataset**.

- **Null Hypothesis ($H_0$):** Smoker and Gender are independent.  
- **Alternative Hypothesis ($H_1$):** Smoker and Gender are not independent.

After applying the Chi-Square Test:

$$
\chi^2 = \sum \frac{(O - E)^2}{E}
$$

If the *p-value* is less than 0.05, we **reject $H_0$**, meaning there is a **significant relationship** between *smoking status* and *gender*.

Otherwise, we **fail to reject $H_0$**, meaning *smoking* and *gender* are **independent** in the Tips dataset.


In [5]:
tabel = pd.crosstab( data['smoker'], data['sex'])
tabel

sex     Male  Female
smoker              
Yes       60      33
No        97      54

In [6]:
def test_for_independence(observed):
    arr_tabel = np.array(observed)
    row_sum = arr_tabel.sum(axis=1)
    column_sum = arr_tabel.sum(axis=0)
    grand_sum = arr_tabel.sum()
    
    expected = np.zeros(arr_tabel.shape)
    
    for i in range(arr_tabel.shape[0]):
        for j in range(arr_tabel.shape[1]):
            expected[i, j] = (row_sum[i] * column_sum[j]) / grand_sum
            
    print("Observed-Table")
    print(arr_tabel)
    print('___________________________________')
    print("Expected-Table")
    print(expected)
    print('___________________________________')
    
    chi_square = ((arr_tabel - expected) ** 2) / expected
    chi_square = chi_square.sum()
    print("Chi-square value")
    print(chi_square)
    print('___________________________________')
    
    print("Degree-of-freedom")
    row = arr_tabel.shape[0]
    column = arr_tabel.shape[1]
    df = ((row - 1) * (column - 1))
    print(df)
    print('___________________________________')
    print("P-value")
    p_value = chi2.sf(chi_square, df)
    print(p_value)
    print('___________________________________')
    print("Conclusion")
    if p_value < 0.05:
        print("✅ H1 Wins")   
    else:
        print("❌ H0 Wins")       

In [7]:
test_for_independence(tabel)
# Since the p-value is greater than 0.05 
# we fail to reject the null hypothesis 
# This means there is no significant relationship 
# between smoker and gender in the Tips dataset — they appear to be independent of each other.

Observed-Table
[[60 33]
 [97 54]]
___________________________________
Expected-Table
[[59.84016393 33.15983607]
 [97.15983607 53.84016393]]
___________________________________
Chi-square value
0.001934818536627623
___________________________________
Degree-of-freedom
1
___________________________________
P-value
0.964915107315732
___________________________________
Conclusion
❌ H0 Wins


In [8]:
titanic = sns.load_dataset('titanic')

In [9]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [12]:
titanic.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

### Example — Chi-Square Test for Independence (Titanic Dataset)

Now, we are working on the **Titanic dataset** to test whether **Survival status (Survived)** has any relationship with **Passenger Class (Pclass)**.

- **Null Hypothesis ($H_0$):** Survived and Passenger Class are independent.  
- **Alternative Hypothesis ($H_1$):** Survived and Passenger Class are not independent.

We will apply the Chi-Square Test for Independence to see if **passenger class** had any significant effect on **survival chances**.


In [14]:
tabel = pd.crosstab(titanic['class'], titanic['survived'])
tabel

survived    0    1
class             
First      80  136
Second     97   87
Third     372  119

In [ ]:
test_for_independence(tabel)
# The Chi-Square test result shows that the p-value is less than 0.05 
# so we reject the null hypothesis 
# This means there is a significant relationship between 
# Survival status and Passenger Class in the Titanic dataset 
# passengers from higher classes were more likely to survive.

Observed-Table
[[ 80 136]
 [ 97  87]
 [372 119]]
___________________________________
Expected-Table
[[133.09090909  82.90909091]
 [113.37373737  70.62626263]
 [302.53535354 188.46464646]]
___________________________________
Chi-square value
102.88898875696056
___________________________________
Degree-of-freedom
2
___________________________________
P-value
4.549251711298793e-23
___________________________________
Conclusion
✅ H1 Wins
